
'use client';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { useAuth } from '@/hooks/use-auth';
import { useRouter, usePathname } from 'next/navigation';
import React, { useEffect } from 'react';

// export const metadata: Metadata = { // Metadata must be defined in a server component
//   title: 'Firebase Studio App',
//   description: 'Generated by Firebase Studio',
//   manifest: '/manifest.json',
// };

const AuthProvider = ({ children }: { children: React.ReactNode }) => {
  const { isLoggedIn } = useAuth();
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    const publicPaths = ['/login', '/register'];
    const pathIsPublic = publicPaths.includes(pathname);

    if (!isLoggedIn && !pathIsPublic) {
      router.push('/login');
    } else if (isLoggedIn && pathIsPublic) {
      router.push('/');
    }
  }, [isLoggedIn, pathname, router]);

  return <>{children}</>;
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const noShellLayout = ['/login', '/register'].includes(pathname);

  return (
    <html lang="en">
      <head>
        <title>Firebase Studio App</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        ></link>
        <meta name="theme-color" content="#f85a6a" />
      </head>
      <body className="font-body antialiased">
          <AuthProvider>
            {noShellLayout ? (
              children
            ) : (
              <main className="flex justify-center items-start min-h-screen bg-gray-100 p-0 md:p-4">
                <div className="w-full max-w-sm mx-auto bg-white shadow-lg rounded-3xl overflow-hidden md:mt-8">
                  {children}
                </div>
              </main>
            )}
          </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
